version: "3.8"

services:
  database:
    container_name: sudoku_db
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      #- sudoku-data:/var/lib/postgresql/data
      - ./backend/db/sql_scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=Aa123456
    networks:
      - sudoku-net

  frontend:
    container_name: sudoku_frontend
    build: ./client
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - sudoku-net

  backend:
    container_name: sudoku_backend
    restart: always
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
    networks:
      - sudoku-net

volumes:
  sudoku-data:

networks:
  sudoku-net:
