version: "3.8"

services:
  database:
    container_name: sudoku_db
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - sudoku-data:/var/lib/postgresql/data
      - ./backend/db/sql_scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=Aa123456
  frontend:
    container_name: sudoku_frontend
    build: ./client
    ports:
      - 80:80
    environment:
      - BACKEND_URL=localhost:3000
  backend:
    container_name: sudoku_backend
    restart: always
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
volumes:
  sudoku-data: